# Generated by Django 2.2.1 on 2019-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_alt', models.CharField(max_length=200)),
                ('img_author', models.CharField(max_length=100)),
                ('img_date', models.DateTimeField()),
            ],
        ),
    ]
