# Generated by Django 2.2.1 on 2019-06-11 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='img_date',
        ),
    ]
