# Generated by Django 2.2.1 on 2019-06-12 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_picture_img_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
